version: '3.3'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - '27017:27017'

  social-active:
    image: khaninejad/social-active:0.0.18
    command: npm run start:prod
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env.prod
    depends_on:
      - mongo
